### ISSUE TITLE
For packages, take the "tests" config from "exposed-modules" in elm.json

### ISSUE THREAD

**Issue by gampleman** [stoeffel/elm-verify-examples#105]
One issue with using this tool over the long run is that you forget you need to update the `elm-verify-examples.json` file with every module you add (this totally happened to me on elm-visualization - I'm dreading how many broken examples I'll find 😢).

However, for packages we already have a list of documented modules - the `"exposed-modules"` option in elm.json. Of course there may be cases where you for some reason don't want `elm-verify-examples` to run on some module, so supporting a manual configuration mode makes sense. But for packages I think this would be a more sensible default preventing this sort of user error.

**Comment by stoeffel** [comment]
I think that makes sense, best would be to find the modules containing examples, but at the time I didn't find a fast solution for that. I would welcome a PR.
