### ISSUE TITLE
Inappropriate handling of elm.json for packages

### ISSUE THREAD

**Issue by arowM** [stoeffel/elm-verify-examples#112]
Thanks for the cool project. 🌷

It seems that the latest v6.0.2 always requires "source-directories" property in `elm.json`, but `elm.json` for packages [does not have "source-directories" property](https://github.com/elm/compiler/blob/master/docs/elm.json/package.md).
Although it works if we set the "source-directories" property in `elm.json` for packages, it would be better behavior to check the "type" property and assume that the "source-directories" is `./src` if the value is `"package"`.

**Comment by stoeffel** [comment]
Oh yes! good catch! thanks.

**Comment by ymtszw** [comment]
Attempted a fix (#113), would appreciate your feedback! @stoeffel
