### ISSUE TITLE
renaming

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/elm-verify-examples#23]
I would like to propose renaming this to something that doesn't emphasises `test`.
The reason behind this is that IMO the goal of this tool is to write better docs/examples and not to write tests.

I can think of a few possible names:

* `elm-verified-docs`
* `elm-verified-examples`
* `elm-verify-examples`
* `elm-check-examples`

**Comment by stoeffel** [comment]
What do people think? cc @zwilias @rtfeldman @eeue56 @cuducos @ohanhi

**Comment by eeue56** [comment]
Renaming is good, but we should make sure to include doc-test somewhwere in the description, so that it's findable

**Comment by stoeffel** [comment]
Yes, mention something like this was formerly known as `elm-doc-test`.

**Comment by stoeffel** [comment]
Any preferences for a name?

**Comment by stoeffel** [comment]
I think I like `elm-verify-docs` best.

**Comment by zwilias** [comment]
I like names of tools to convey what they _do_ rather than the end goal, so in that sense, I prefer `elm-verify-docs` or `elm-verify-examples` (since it verifies the examples, not the prose).

**Comment by stoeffel** [comment]
Yop, I like `elm-verify-examples` even more!
