### ISSUE TITLE
testing view functions

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/elm-verify-examples#25]
*turn this into an actual issue*

if the expected value is html or the type of the left side is `Html`.

```elm
{-|
    viewButton "foo"
    --> <div><button>foo</button>...</div> <= ... is ignored? special sytax for html
-}

**Comment by mgold** [comment]
Useful library: [elm-html-test](http://package.elm-lang.org/packages/eeue56/elm-html-test/latest).

**Comment by stoeffel** [comment]
Would be useful for http://package.elm-lang.org/packages/NoRedInk/view-extra/2.0.0/View-Extra.

**Comment by scottcorgan** [comment]
If I could test my views in my comments like this, I'd fly to Europe and give you a hug @stoeffel!

**Comment by eeue56** [comment]
Need to discuss a bit more what the expectation should look like

**Comment by stoeffel** [comment]
yeah it would be useful to find many usecases in current docs and see how they look like.
