### ISSUE TITLE
Multiple examples require newline

### ISSUE THREAD

**Issue by mgold** [stoeffel/elm-verify-examples#32]
This produces a test that fails to compile:

```
    foldl1 (++) (Nonempty "a" ["b", "c"]) --> "cba"
    foldl1 (++) (fromElement "a") --> "a"
```

If I insert a newline between these, then it compiles and runs as expected.

Ideally the newline would not be necessary, and at a minimum this should be documented (it's not obvious that two examples are permitted at all!).

**Comment by stoeffel** [comment]
oh, didn't think that one wouldn't add a newline. this should be documented and maybe we find a solution to not need the newline at all later

**Comment by stoeffel** [comment]
@mgold I updated the docs

**Comment by mgold** [comment]
Thanks for this and the other fixes!

**Comment by stoeffel** [comment]
😊! let me know how you like using it. I'm​super happy that some people find it useful and I really appreciate feedback to make it better.

**Comment by mgold** [comment]
Yeah, I was dimly aware of `elm-doc-test` but it never really clicked what it did. Between the new name and brilliant `-->` syntax, I think this is a really promising tool. I'll file issues for any other ideas I have.
