### ISSUE TITLE
Extract examples from the README

### ISSUE THREAD

**Issue by mgold** [stoeffel/elm-verify-examples#34]
It would be helpful if examples from the README were extracted into their own tests, probably in a `Readme.elm` module. I think if you looked for backtick code fences with `elm` on the end, the parsing shouldn't be too hard. You can also have a flag in the JSON to enable/disable this.

See [this README](https://github.com/mgold/elm-nonempty-list#listnonempty-for-elm) which has some examples that could easily be converted into the `-->` style.

**Comment by stoeffel** [comment]
That's an awesome idea!

**Comment by stoeffel** [comment]
it should extract examples from any markdown file, not just from the Readme

**Comment by mgold** [comment]
Sure, let it take a list of markdown files in the JSON file.

**Comment by gampleman** [comment]
This is completed in #58 as far as I can tell. Feel free to reopen if there is something more missing here.
