### ISSUE TITLE
Proposal: Using elm-tools/parser for parsing

### ISSUE THREAD

**Issue by ohanhi** [stoeffel/elm-verify-examples#36]
At the moment elm-verify-examples is using Regex for parsing the doc comment contents. [elm-tools/parser](http://package.elm-lang.org/packages/elm-tools/parser/latest) seems like a very nice way to parse things in Elm. 

Do you think it would be an interesting experiment if I tried rewriting (at least a part of) the parsing using that library instead of regular expressions?

**Comment by eeue56** [comment]
Go for it, but be sure to benchmark. See this PR for more info: https://github.com/stoeffel/elm-verify-examples/pull/9

**Comment by stoeffel** [comment]
I was thinking about doing that as well. Please go for it!
