### ISSUE TITLE
Extract tests

### ISSUE THREAD

**Issue by mgold** [stoeffel/elm-verify-examples#37]
Elm-test docs include some examples of tests. It would be helpful is these could be lifted directly into a test file.

This is definitely low priority because there isn't much use outside of elm-test itself.

**Comment by gampleman** [comment]
As far as I understand, the ask here is to turn something like:


```elm
{-| Produces a fancy expectation

    myTest : Test
    myTest =
       test "foo" <|
          \() ->
              foo
                 |> FooExpectation.fancy
-}
fancy : Foo -> Expectation
fancy foo = 
    Expect.fail ""
```

into

```elm
module VerifyExamples.FooExpectation.FancyTest0 exposing (myTest)

import FooExpectation

myTest : Test
myTest =
    test "foo" <|
        \() ->
            foo
                |> FooExpectation.fancy
```
?


---

What's your thought @stoeffel?

In my mind this seems a bit out of scope. a) the exampley function only works for testing libraries, which is a fairly small use case b) it encourages writing elaborate tests in comments, which seems like an anti pattern.

**Comment by stoeffel** [comment]
I think that it would move the tool more towards a test replacement instead of verifying docs.
