### ISSUE TITLE
Bug: Malformed example causes rest of comment to be ignored

### ISSUE THREAD

**Issue by daphee** [stoeffel/elm-verify-examples#40]
There is a bug in Parser.elm#astToTestSuite that lets a malformed example cause the rest of the comment to be ignored. 

To reproduce this bug change the comment for the `foo` method in `example/Mock/Foo/Bar/Moo.elm` to this:

```
{-| does stuff

    foo "a" "b" "c"
    --> "bca"

    --> 2

    --> 2

    foo "a" "b" "!" --> "b!a"

-}
```

If you now run `run-tests.sh` the output will read that the test suite only contains 15 instead of 16 tests. 

This bug is caused by the `case` in `astToTestSuite`. The above comment will be parsed to a `List Ast` containing two successive `Expectation String`. This case is not handled and will lead to line 41 be executed and `toTests` returning. 

This can be solved by changing the `toTests` method to this:

```
toTests : List Test -> List Ast -> List Test
        toTests acc xs =
            case xs of
                (Assertion x) :: (Expectation y) :: rest ->
                    toTests
                        ({ assertion = x
                         , expectation = y
                         }
                            :: acc
                        )
                        rest

                _ :: rest ->
                    toTests acc rest

                _ ->
                    acc
```

which drops items from `xs` until it finds a valid sequence of items.

**Comment by stoeffel** [comment]
Good catch! I think your solution should fix this. @daphee would you like to create a PR? I would highly appreciate that 👍
