### ISSUE TITLE
Parse all files for examples.

### ISSUE THREAD

**Issue by akoppela** [stoeffel/elm-verify-examples#62]
When the project is big it's nice to have a regex to parse all files for examples.

**Comment by lzrski** [comment]
Since all examples have specific syntax (the `--> ...` part) maybe it should be a default behavior?

**Comment by stoeffel** [comment]
I'm happy to accept a PR, but I'm worried about performance. I don't think parsing `-->` is enough, because that might appear in application code as well.

**Comment by knuton** [comment]
Implemented in #110
