### ISSUE TITLE
Add an option to not run tests

### ISSUE THREAD

**Issue by Hywan** [stoeffel/elm-verify-examples#65]
Hello,

Thanks for this project!

Right now, `elm-verify-examples` compiles examples as tests, and then run them. If examples are compiled in the `tests/` directory, then it's likely they will be run by `elm-test` “manually” in another pass. Indeed, I think it's expected to see the user doing this:

```bash
$ elm-verify-examples --no-test-run … # Compile examples to tests
$ elm-test # Run all tests
```

Thoughts?

**Comment by stoeffel** [comment]
Hi!
I think this is a good idea!
I think I would name the flag `--only-generate-tests` or something like that though.

**Comment by Hywan** [comment]
Indeed, that's a better option name :-).

**Comment by lzrski** [comment]
Great idea! This would enable easy integration with other test runners, like `elm-coverage`.

And perhaps in the next major release it could be the only thing this project does? Do one thing and do it well 🧙‍♂️

**Comment by stoeffel** [comment]
How about inversing the flag and naming it `--run-tests` instead. Default is to not run them and with the flag you can pass it a test runner.

**Comment by lzrski** [comment]
I'd like that.
