### ISSUE TITLE
Support multiple root paths.

### ISSUE THREAD

**Issue by akoppela** [stoeffel/elm-verify-examples#67]
Sometimes Elm code is located under different root paths. It would be nice to specify and array of root paths. Same way as `source-directories` in `elm-package.json`.

**Comment by lzrski** [comment]
Would it make sense to just read it from `elm.json`?

Together with #62 it would make elm-verify-examples work without any configuration. Just run and see the tests' results!

**Comment by akoppela** [comment]
yes, it's nice to have no configuration

**Comment by stoeffel** [comment]
SGTM!

**Comment by knuton** [comment]
Supported with #110
