### ISSUE TITLE
Wrong elm.json format?

### ISSUE THREAD

**Issue by amitaibu** [stoeffel/elm-verify-examples#75]
I tried to copy https://github.com/stoeffel/elm-verify-examples/blob/f485accfdea6e13c853503e78d739dc478a0a3c5/elm.json#L22-L29

into my elm.json but got 

```
-- BAD JSON ----------------------------------------------------------- elm.json

The object at project['test-dependencies'].direct is causing issues.

I was expecting a STRING.
```

I then changed it to this, which worked: 

```
    "test-dependencies": {
        "elm-explorations/test": "1.0.0 <= v < 2.0.0"      
    }
```

**Comment by FranklinChen** [comment]
You were probably creating a "package" rather than an "application". I just got bitten by this and found out that the JSON syntax differs: https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md#elmjson
