### ISSUE TITLE
Solution on failing elm-verify-examples on Travis

### ISSUE THREAD

**Issue by amitaibu** [stoeffel/elm-verify-examples#76]
Hoping this may save some time to others. It seems that on Travis `elm-test@0.19.0-beta8` is working fine, but `elm-test@0.19.0-beta9` causes the tests to hang.

As `elm-verify-examples` (in short `eve`) has a dependency on `beta` https://github.com/stoeffel/elm-verify-examples/blob/f485accfdea6e13c853503e78d739dc478a0a3c5/package.json#L38 it causes a case where even if you hardcoded the elm-test to the beta8, then `eve` would still run it in the wrong version.

![build__57_-_gizra_elm-storage-key_-_travis_ci](https://user-images.githubusercontent.com/125707/45931449-fb6beb00-bf76-11e8-9a3c-619b444a5dcd.jpg)

So here's my solution, to explicitly call the global elm-test

https://github.com/Gizra/elm-storage-key/pull/3/commits/d89f3b3ffddfc75dcc9aaa2a12cfafb851291289

**Comment by stoeffel** [comment]
I've just published 3.0.1 and changed the dependency to https://github.com/stoeffel/elm-verify-examples/blob/master/package.json#L38.
@amitaibu would you mind testing again?

**Comment by amitaibu** [comment]
Sure, I'll try in https://github.com/Gizra/elm-editable-webdata/pull/5 - I'm just upgrading it

However, I think that `^0.19.0-beta8` will still end up with beta9 (unless you'll remove the `^`)

**Comment by amitaibu** [comment]
Actually it worked fine, Thanks!
