### ISSUE TITLE
elm-verify-examples 3.0.1 hangs in Linux on Travis CI

### ISSUE THREAD

**Issue by billstclair** [stoeffel/elm-verify-examples#77]
`elm-verify-examples` version 3.0.1 hangs in Linux on Travis CI.

It's running into the `elm-test` hang problem with `elm-test@elm0.19.0-beta9`, which it is getting since `package.json` specifies `"^0.19.0-beta8"`, which actually fetches `0.19.0-beta9`.

It would probably work if you changed the version to `"elm0.19.0"`, which is currently a nickname for beta8, and will likely be updated as newer versions become stable.

I have no easy way to test this, since it works fine in my Ubuntu 18.04 VM, just not on Travis.

See https://travis-ci.org/billstclair/elm-xml-eeue56 for an example. Works fine in MacOS, but hangs in Linux.

**Comment by billstclair** [comment]
elm-test version 0.19.0-beta10 purportedly fixes the hang (I haven't tried it). If you change the dependency to version "elm0.19.0", you'll get that one, and any future 0.19 releases.

**Comment by ymtszw** [comment]
Fix confirmed with `--elmtest=elm-test` option (assuming you have `elm-test` in your `PATH`).
Also, `elm-test@0.19` is officially released now.
BTW thanks for this tool @stoeffel , I'm using this in my [elm-xml-decode](https://github.com/ymtszw/elm-xml-decode)!

**Comment by gampleman** [comment]
I think this is now fixed.
